# Generated by Django 2.2.7 on 2019-12-07 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('link', models.CharField(max_length=500)),
                ('order', models.IntegerField()),
                ('created', models.DateTimeField(null=True)),
                ('is_active', models.NullBooleanField(default=False)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=250)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/product')),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=250)),
                ('stock', models.IntegerField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/employee')),
                ('price', models.FloatField(max_length=100)),
                ('created', models.DateTimeField(null=True)),
                ('is_active', models.NullBooleanField(default=False)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('modified', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomadminapp.ProductCategory')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.CompanyRegistration')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomadminapp.Promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
